# Minimal service configuration
---
llm_providers:
  - name: my_bam
    type: bam
    url: "http://wont-be-used"
    models:
      - name: ibm/granite-3-8b-instruct
ols_config:
  conversation_cache:
    type: memory
    memory:
      max_entries: 1000
  logging_config:
    app_log_level: info
    lib_log_level: warning
  default_provider: my_bam
  default_model: ibm/granite-3-8b-instruct
dev_config:
  enable_dev_ui: false
  disable_auth: true
  disable_tls: true

